[SPEC2017] Add -fcommon to build ldecod in x264
As stated in
https://www.spec.org/cpu2017/Docs/benchmarks/525.x264_r.html#portability,
building ldecod requires -fcommon as -fno-common is the default;
otherwise linking errors like the following will occur.

```
/usr/bin/ld: .../525.x264_r/decoder_test.c.o:(.bss+0x0): multiple definition of `cfgparams'; .../525.x264_r/configfile.c.o:(.bss+0x0): first defined here
/usr/bin/ld: .../525.x264_r/config_common.c.o:(.bss+0x0): multiple definition of `cfgparams'; .../525.x264_r/configfile.c.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
```

Differential Revision: https://reviews.llvm.org/D139658