[External][SOLLVE_V&V] Disable failing test.
Un-whitelist the test 5.0/target/test_target_allocate.c which has been
changed upstream in is now failing with

    test_target_allocate.c:27:32: error: allocator must be specified in the 'uses_allocators' clause
        #pragma omp target allocate(omp_default_mem_alloc:x) firstprivate(x) map(from: device_result)
                                    ^~~~~~~~~~~~~~~~~~~~~

Responsible upstream commit (https://github.com/SOLLVE/sollve_vv/commit/f129edeb595668056a7d117b0f00db40a05dd48e):

    commit f129edeb595668056a7d117b0f00db40a05dd48e
    Author: Seyong Lee <lees2@ornl.gov>
    Date:   Fri Mar 11 12:10:04 2022 -0500

        Add new_test/test_target_allocate.F90. (#460)

        * Add new_test/test_target_allocate.F90.
        Test fails with both GCC11.1.0 and XLF16.1.1-10 (not supported).

        * add the default allocator expression to the allocate clause (allocate(omp_default_mem_alloc: x)) in both C and Fortran versions.